theme = "hugo-sugoi"
baseURL = "https://simonschoof.com"
languageCode = "en-us"
title = "Simon Schoof"
summaryLength = 20
paginate = 5
enableEmoji = "true"
enableRobotsTXT = true

[params]
favicon = "images/favicon.png"
herotitle = "Moin Moin!"
herolink = "https://github.com/simonschoof/hugo-sugoi"
herolinktext = "Check Now"
herobackgroundimage = "images/hero_background_hafen.webp"
headertext =  "Home"



[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-user'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2
