theme = "hugo-sugoi"
baseURL = "https://example.com"
languageCode = "en-us"
title = "Simon Schoof"
summaryLength = 20
paginate = 5

[params]
favicon = "images/favicon.png"
herotitle = "SIMONSCHOOF.COM"
herolink = "https://github.com/simonschoof/hugo-sugoi"
herolinktext = "Check Now"
herobackgroundimage = "images/hero_background_hafen.webp"
headertext =  "simonschoof.com"
contact = "Send me a message and I will get back as soon as possible."

[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2
    [[menu.nav]]
        name    = "contact"
        pre = "<i class='fas fa-envelope'></i>"
        url     = "contact"
        weight  = -3
