theme = ["hugo-cloak-email", "hugo-sugoi"]
baseURL = "https://simonschoof.com"
languageCode = "en-us"
title = "Simon Schoof"
summaryLength = 20
paginate = 5
enableEmoji = "true"
enableRobotsTXT = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 4

[taxonomies]
  tag = "tags"
  series = "series"

[params]
favicon = "images/favicon.png"
herotitle = "Moin Moin!"
herolink = "https://github.com/simonschoof/hugo-sugoi"
herolinktext = "Check Now"
herobackgroundimage = "images/hero_background_hafen.webp"
headertext =  "Home"

[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-user'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "post"
        weight  = -2
    [[menu.nav]]
        name    = "github"
        pre = "<i class='fab fa-github'></i>"
        url     = "https://github.com/simonschoof"
        weight  = -3
    [[menu.nav]]
        name    = "mastodon"
        pre = "<i class='fab fa-mastodon'></i>"
        url     = "https://social.simonschoof.com/@connect"
        weight  = -4